### ISSUE TITLE
Bug reports and some suggestions

### ISSUE THREAD

**Issue by ianvitornp** [zend10/AL-chan#42] opened 2021-03-06 17:56 UTC
Bugs:
1. Using the grid option, the progress indicator sometimes goes wrong (sometimes this gets resolved when I update the list).
![IMG_20210306_141822](https://user-images.githubusercontent.com/74222213/110215186-3207f880-7e87-11eb-8c35-68303f1a826a.jpg)
![IMG_20210306_141856](https://user-images.githubusercontent.com/74222213/110215187-33392580-7e87-11eb-8af2-bad8963f7531.jpg)

2. When you press an anime tag, enter another anime for it and come back, instead of showing other anime with that tag, the app goes back to the original anime. Video for better understanding: https://youtu.be/e_cZxjWCv9g

3. Tag percentage does not work on lists. Demonstration: https://youtu.be/n_CzE9nLcUw

4. The score distribution on the profile page is not very sure, it only shows whole numbers (even if I score an anime like 7.5). Also, when I reset my scores and update my data, my scores continue to be shown, even though my mean score is 0.0

5. The app does not show the following relations: Contain, Compilation (are considered as Other) and Source (considered as Adaptation)
![IMG_20210306_143124](https://user-images.githubusercontent.com/74222213/110215548-287f9000-7e89-11eb-8bb8-de68a409f6ed.jpg)
![IMG_20210306_143406](https://user-images.githubusercontent.com/74222213/110215549-29b0bd00-7e89-11eb-88fd-d8f23b761eb2.jpg)
![IMG_20210306_143158](https://user-images.githubusercontent.com/74222213/110215550-2a495380-7e89-11eb-9a2d-b3dc6d72cefb.jpg)
![IMG_20210306_143427](https://user-images.githubusercontent.com/74222213/110215551-2ae1ea00-7e89-11eb-9dff-29f7799ec346.jpg)
![IMG_20210306_143132](https://user-images.githubusercontent.com/74222213/110215552-2ae1ea00-7e89-11eb-89f4-b03f1a5e0756.jpg)
![IMG_20210306_143335](https://user-images.githubusercontent.com/74222213/110215555-2b7a8080-7e89-11eb-8af1-e22cb6336656.jpg)

Sugestions:
1. Option to hide the "Releasing Today" tab. The "+1" button is dangerous (i may accidentally tap it)

2. We have the option to hide the progress of chapters and volumes in the manga list, but we don't have to hide that of the episodes. It would be nice if there was too.

3. Add the other types of lists in other places, for example: in the list of other users and in the seasonal chart (it is only possible to switch between the grid option and the linear option) And it would also be nice to see these types of lists in the Explore tab as well.

4. In the social tab, our icon is circular. It would be nice to be able to leave it square, just as we can leave the circular icon on the profile page.
![IMG_20210306_145016](https://user-images.githubusercontent.com/74222213/110215984-4a7a1200-7e8b-11eb-8dd8-a7917d631f7f.jpg)

5. In the calendar tab, the options we choose should be permanent, sometimes I go there to see what anime launches today, but I have to disable the option "Show only Anime in your Watching and Planning list".

**Comment by zend10** [comment] 2021-03-08 13:53
Okay this is a long one. I'll be taking my time reply this more in detail.

**Comment by zend10** [comment] 2021-03-09 13:37
Bugs:
1. Yeah, I need to address this sooner or later.
2. It's actually the intended behavior. If I don't close the Explore page, you can click on the tag in media page, it'll open another Explore page, then you can click on a media, then click on the tag again, then open another Explore page, and so on. I'm not very sure the most optimal way to handle this. I'll think more about this.
3. I'll be looking into it.
4. Yup, aware of it #11. Actually difficult to solve. :(
5. Oh, the API is updated and I'm not aware of it. Thanks.

Suggestions:
1. Okay, maybe.
2. Probably not very useful to be honest. Having a list but not showing the episode progress seems too weird.
3. Yeah, reasonable.
4. I don't think it will fit the whole design of the app. 
5. Yeah, a good one.

**Comment by zend10** [comment] 2023-07-03 18:10
I'm sorry I have to close this for now. If still needed, can create each of them in separate thread for easier tracking.

**Closed by zend10** 2023-07-03 18:10 UTC
Labels: bug, enhancement
