### ISSUE TITLE
[UI-Bugs] - Redmi Note 7 [Overlapped text]

### ISSUE THREAD

**Issue by ElFrostburnMC** [zend10/AL-chan#15] opened 2020-08-28 19:09 UTC
There are some UI Bugs on Xiaomi's Redmi Note 7 (Based on some screnshoots from other users I think they don't have to look like that), which are pretty annoying, the device has a FullHD+ 2,340 x 1,080 display and it's using MIUI 11 based on Android 10
![IMG_20200826_142948](https://user-images.githubusercontent.com/65023891/91605855-6f884800-e971-11ea-9fc7-f85f0cc67217.jpg)
![IMG_20200826_195444](https://user-images.githubusercontent.com/65023891/91605860-70b97500-e971-11ea-8a16-895893798518.jpg)
![IMG_20200826_193033](https://user-images.githubusercontent.com/65023891/91605862-71520b80-e971-11ea-9e2b-fa4fa69aeb8c.jpg)
In the image below, I have one Anime on Watching (or Current) and another one on Paused, so I think it's a bug as it isn't well displayed on the chart:
![IMG_20200826_143530](https://user-images.githubusercontent.com/65023891/91606465-65b31480-e972-11ea-9180-b4c6cf936cec.jpg)

**Comment by zend10** [comment] 2020-08-29 10:51
1. I've always been thinking about using images for that "Seasonal", "Explore", and "Reviews". I'm a terrible graphic designer though, so I've been postponing it all the time.

2. Do you perhaps change the font size of your phone? I'll need to make sure first.

3. Same question as above. I'm not sure why this title can be chopped off like that. I'll need to make sure first as well.

4. Have you checked the stats from the website? AniList doesn't provide real time data. You'll need to wait for a day or two.

**Comment by ElFrostburnMC** [comment] 2020-08-29 11:28
Oh, I checked the font size and turns out that changing (decreasing) the size from "L" to "M"
![IMG_20200829_132626](https://user-images.githubusercontent.com/65023891/91635746-4ca27600-e9fb-11ea-9042-ed1fa7896303.jpg)
fixes the UI issues except for the "Seasonal Chart" which is still a bit weird,
![IMG_20200829_132009](https://user-images.githubusercontent.com/65023891/91635662-8aeb6580-e9fa-11ea-8725-6d7932b27d29.jpg)
 I think it could be fixed if I decrease more the font size but I don't want to do it as it also decreases all the System UI Font sizes, maybe you should consider adding a "Font Size Selector" for Al-Chan which doesn't modify the System's UI, only the App's UI

And for the Website Stats, those animes have been in that Status for at least 1 week, I've also made sure that the Stats from Anilist's website are updated, and they are, so I don't know what to do.

**Comment by zend10** [comment] 2020-08-29 14:36
I'll be updating those menu with images. Wish me luck with that.

About the stats, have you tried force updating in your Settings > Lists? You have to do it from the web. It's surely not a bug in the application, I can ensure you that. I have no idea why AniList have been taking their time with updating the stats. Probably they have some internal issue at the current time. Usually it's around 24 hours or more.

So, try force updating it might help.

<img src="https://cdn.discordapp.com/attachments/749274804925759548/749274887314735134/update_stats.png" width="50%">

**Comment by ElFrostburnMC** [comment] 2020-08-29 15:03
Well, I did it several times as you can see (yes, in the web) 
![IMG_20200829_164230](https://user-images.githubusercontent.com/65023891/91639467-18d54980-ea17-11ea-96ac-074c817aa8b0.jpg)
but it is still not showing as it should, so I think it's probably their issue
![IMG_20200829_164614](https://user-images.githubusercontent.com/65023891/91639528-808b9480-ea17-11ea-9eaa-0d580d5a0c50.jpg)
I've noticed that it shows the same chart on anilist's web page so it's probably their issue:
![IMG_20200829_165447](https://user-images.githubusercontent.com/65023891/91639678-951c5c80-ea18-11ea-8697-e3ad3ba31602.jpg)
Anyway, sorry for bothering you about an issue which doesn't exist on your app because it's Anilist's problem.

And another question, should I open another Issue with this suggestion?:
![IMG_20200829_165827](https://user-images.githubusercontent.com/65023891/91639722-e298c980-ea18-11ea-9328-76c3b14aaf2b.jpg)

I think it can fix UI problems on some devices as mine without having to change the whole Android Font Size, as it would only change the App's font size.

**Comment by zend10** [comment] 2020-08-29 15:46
Don't worry, it's common to not know about the stats issue. 

I'm not very sure about letting user change the font size. It feels too overkill. I think I will simply restrict the system from changing the font size in some area, mainly from anime and manga list this time.

**Comment by zend10** [comment] 2020-09-09 17:58
Fixed on v.1.1.3.

**Closed by zend10** 2020-09-09 17:58 UTC
Labels: bug, implemented
